### ISSUE TITLE
神保町食肉センター上野店(夜)

### ISSUE THREAD

**Issue by nshiba** [cpslab/MonthlyMeshi#1]
[公式サイト](http://www.post.co.jp/store/%E5%8D%B8%EF%BC%89%E7%A5%9E%E4%BF%9D%E7%94%BA%E9%A3%9F%E8%82%89%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC-%E4%B8%8A%E9%87%8E%E5%BA%97/)  
## 予算

¥2,500~
むにたんの話だと酒と肉で¥4,000くらい

**Comment by nshiba** [comment]
上野

**Comment by akameco** [comment]
情報なさすぎて何も伝わらねぇ...

**Comment by nshiba** [comment]
@akameco 夜に食肉に行ってうまい🍖食いてぇよなぁ

**Comment by munisystem** [comment]
せめて値段と食べログかなんかのリンクは貼りません？

**Comment by nshiba** [comment]
ｻｰｾﾝ

**Comment by Nshiba** [comment]
[公式サイト](http://www.post.co.jp/store/%E5%8D%B8%EF%BC%89%E7%A5%9E%E4%BF%9D%E7%94%BA%E9%A3%9F%E8%82%89%E3%82%BB%E3%83%B3%E3%82%BF%E3%83%BC-%E4%B8%8A%E9%87%8E%E5%BA%97/)  
## 予算
公式サイトによると¥2,500~らしい  
この前のむにたんの話だと酒と肉で¥4,000くらいかな？

**Comment by munisystem** [comment]
画像で破壊力を生み出そう 🔥
![chcj5g-ugaa73lb](https://cloud.githubusercontent.com/assets/7877005/15843642/bed0f608-2c9e-11e6-937b-80094383039a.jpg)

**Comment by nshiba** [comment]
うまそう…
